manifest:
  remotes:
    - name: zmkfirmware
      url: https://github.com/zmkfirmware/zmk
    # Add this if it's missing
    - name: petejohanson
      url: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Add this if you are using nice_view
    - name: zmk-helpers
      remote: petejohanson
      revision: main